# Singaporean Food in Indonesia Phrase II : Jawa and Bali Area

For this notebook I'll show you list of Singaporean restaurant in Jawa (Bandung, Semarang, Sleman, Surabaya, Malang, Batu) and Bali Area (Badung, Denpasar). Here is the list curated from Google Maps and various platform website. This time I'll be using Pergi Kuliner, Traveloka Eats, Tripadvisor, and Restaurant Guru.

Originally there are 101 restaurants selected all around Indonesia, which 38 of them are located in this area. Note that the list here is not always the authentic one. There are coffee shop named Kopitiam and Chinese restaurant which has Singaporean food but never claimed themselves as Singaporean restaurant. At least they got kaya toast, hainanse rice, laksa, chili crab and etc, will explain more on menu.

# Content
* Region-City
* Menu
* Facility
* Rating

In [19]:
from pandasql import sqldf
import pandas as pd
singapore = pd.read_csv("../input/singapore-food/singapore_id.csv", sep = ";")

In [2]:
singapore = sqldf("""SELECT no, restaurant_name, region, city, unique_menu, price, ltrim(google_rating) as google_rating, ltrim(platform_rating) as platform_rating 
FROM singapore 
WHERE city = 'Bandung' OR region = 'Central Java' OR region = 'DI Yogyakarta' OR region = 'East Java' OR region = 'Bali'""")
singapore.style.hide_index()

# Menu

Singapore is famous for their Laksa as also most mentioned here in this list. Besides, they are also famous for their toast-- kaya toast especially, and hainanse rice. Their noodles are their most mainstream here as their food is kind of fusion with Chinese cuisine, like mee goreng, wonton noodle, and kway teow. Curry noodle and bakuteh are underrated but that's the real signature here. Not to mention their seafood is also well known-- chili crab for example.

I'll divide those menu on three category, which is Rice & Noodle Menu, Poultry Menu, and Toast & Snack Menu.

**Rice & Noodle**

Here is their rice and noodle menu. For the rice they mostly have hainanse rice, fried rice, and nasi lemak. Plate rice is rice with side dish on a plate-- it could be anything. They also have porridge as well. For noodle they mostly have laksa, mee goreng, curry noodle, and wonton noodle. There are also mee shua, mee siam, ifumie (crispy noodle), chop noodle, hokkien mee, and noodle soup.

For disambiguation (next time you look for the menu), mee is mie/noodle, fried rice is nasi goreng, kway teow is kwetiaw, beehoon is bihun, and hainanse rice is nasi hainam. Bakmi ayam is quite similar with wonton noodle but it's different after all.

In [5]:
singapore  = sqldf("""SELECT restaurant_name, city, rice_menu, noodle, noodle_specific
FROM singapore
WHERE city = 'Bandung' OR region = 'Central Java' OR region = 'DI Yogyakarta' OR region = 'East Java' OR region = 'Bali'""")
singapore.style.hide_index()

**Poutry Menu**

Here is all the meat menu, mostly chicken. I wrote the cooking method and sauce for chicken, mostly fried and the sauce is mainly dominated by sweet sour and kungpao. Kolokee sauce is also available here.

The seafood are usually provided both on high end or budgeted restaurant like kopitiam. Mostly crab, prawn, and fish. There are several places which serving beef, pigeon, pork and duck menu. For plant based they also have tofu and vegatables menu. Output labeled 'yes' means that they have those menu but just as a topping/out of the menu, except pork for dietary restrictions. Xin Yi Bakuteh and Cacayo Pakuwon Mall are two of them.

In [7]:
singapore  = sqldf("""SELECT restaurant_name, city, chicken, seafood, poultry_other
FROM singapore
WHERE city = 'Bandung' OR region = 'Central Java' OR region = 'DI Yogyakarta' OR region = 'East Java' OR region = 'Bali'""")
singapore.style.hide_index()

**Toast & Snack Menu**

Toast is also one of Singaporean delicacy --for exact is kaya which most mentioned here. The other popular toast menu are peanut, butter, chocolate, and cheese.

Snack dish is the other light menu (could be appetizer as well) on the list available. There are dumplings, spring roll, dimsum (shumai, hakau, mantau, cakwe etc), banana fritter, fries (french fries, cassava) and many more.

In this section, toast and snack are listed separately.

In [9]:
singapore  = sqldf("""SELECT restaurant_name, city, toast
FROM singapore
WHERE city = 'Bandung' OR region = 'Central Java' OR region = 'DI Yogyakarta' OR region = 'East Java' OR region = 'Bali'""")
singapore.style.hide_index()

In [11]:
singapore  = sqldf("""SELECT restaurant_name, city, snack_dish
FROM singapore
WHERE city = 'Bandung' OR region = 'Central Java' OR region = 'DI Yogyakarta' OR region = 'East Java' OR region = 'Bali'""")
singapore.style.hide_index()

# Facility

All restaurant providing takeaway options but only half of them providing delivery options. Most of them has outdoor seat but smoking area are minimum, note that outdoor seat could also be a smoking area. There are six vendors serving alcohol like beer or wine. Wifi is rarely available here.

In [13]:
singapore  = sqldf("""SELECT restaurant_name, city,restaurant_name, city, takeaway, delivery, outdoor_seat, smoking_area, alcohol_served, wifi
FROM singapore
WHERE city = 'Bandung' OR region = 'Central Java' OR region = 'DI Yogyakarta' OR region = 'East Java' OR region = 'Bali'""")
singapore.style.hide_index()

# Rating

These ratings are ordered by highest total rating, should they have more than 3.5 then the restaurant is worth to try. All the facility and menu are representated by all both google and platform rating and count, so in the meantime only ratings are counted here. Based on the results, Shuang Xi Canggu, Little Singapore, and Dapur Panda are the top 3 and all in Badung city of Bali.

Based on the area, Merlion Singapore Mee Mall Olympic Garden (Malang) is scored high (4,8) eventhough judging from the place they're not really that proper as they are in foodcort area. In Surabaya there is Xiang Jia Kopitiam Gwalk which the best among area (scored 4,70). Highest rating available in Semarang is Wee Nam Kee (score 4.25) as well as Xin Yi Bakuteh in Bandung (scored 4.2). Tasty Singapore Kitchen is the only one Singaporean restaurant in Yogyakarta area (scored 4.75)

Bali region has Shuang Xi Bali Canggu as representative as well as in Badung (scored 5), for Denpasar they have PAW Nasi Hainam Cabang B8 for the highest rating in area (scored 4,7).

NA labeled here are the restaurant who doesn't have another ratings besides of google/platform ratings.

In [20]:
singapore = sqldf("""SELECT restaurant_name, city, google_rating, platform_rating, (google_rating + platform_rating)/2 as total_rating,
CASE
	WHEN (google_rating + platform_rating)/2 >= 3.5 THEN "Recommended"
    ELSE "Reconsider"
END AS "Recommendation"
FROM singapore WHERE city = 'Bandung'  OR region = 'Central Java' OR region = 'DI Yogyakarta' OR region = 'East Java' OR region = 'Bali'
ORDER BY total_rating DESC""")
singapore

,restaurant_name,city,google_rating,platform_rating,total_rating,Recommendation
0,Shuang Xi Bali Canggu,Badung,5.0,5.0,5.00,Recommended
1,Little Singapore by Chef Bernard,Badung,4.9,5.0,4.95,Recommended
2,Dapur Panda,Badung,4.8,5.0,4.90,Recommended
3,BAIJI Singaporean Chicken Rice,Badung,4.8,5.0,4.90,Recommended
4,Merlion Singapore Mee Mall Olympic Garden,Malang,4.6,5.0,4.80,Recommended
5,Atlas Kitchen & Coffee Canggu,Badung,4.6,5.0,4.80,Recommended
6,Tasty Singapore Kitchen,Sleman,4.5,5.0,4.75,Recommended
7,Lai Lai Chinese Food,Badung,4.7,4.8,4.75,Recommended
8,PAW Nasi Hainan Cabang B8,Denpasar,4.5,4.9,4.70,Recommended
9,Xiang Jia Kopitiam Gwalk,Surabaya,4.8,4.6,4.70,Recommended
10,Fat Choi Noodle,Surabaya,4.5,4.8,4.65,Recommended
11,Mie Udang Singapore,Surabaya,4.5,4.7,4.60,Recommended
12,Bangi Kopitiam Malang,Malang,4.2,5.0,4.60,Recommended
13,Ka Soh Resto Pakuwon Supermall,Surabaya,4.4,4.6,4.50,Recommended
14,Niki Kopitiam Batu,Batu,4.5,4.5,4.50,Recommended
15,Kedai Singapura,Badung,4.5,4.5,4.50,Recommended
16,Wee Nam Kee Semarang,Semarang,4.5,4.0,4.25,Recommended
17,Niki Kopitiam Malang,Malang,4.5,4.0,4.25,Recommended
18,Xin Yi Bakuteh,Bandung,4.4,4.0,4.20,Recommended
19,SING Bakuteh Semarang,Semarang,4.4,4.0,4.20,Recommended
20,Old Town White Coffee,Semarang,4.2,4.2,4.20,Recommended
21,Laksa 63,Bandung,4.5,3.8,4.15,Recommended
22,Cacayo Pakuwon Mall,Surabaya,4.2,4.1,4.15,Recommended
23,Singapore Resto & Cafe,Bojonegoro,4.3,4.0,4.15,Recommended
24,Wee Nam Kee Chicken Rice Pakuwon Mall,Surabaya,4.5,3.7,4.10,Recommended
25,Mi Hotplet Grand City Mall,Surabaya,4.0,4.0,4.00,Recommended
26,Wee Nam Kee Chicken Rice Tunjungan Plaza,Surabaya,4.2,3.8,4.00,Recommended
27,Sagoo Kitchen & Kopi Lay,Bandung,4.4,3.5,3.95,Recommended
28,Old Kettle,Semarang,4.4,3.5,3.95,Recommended
29,My Kopi O!,Semarang,4.4,3.5,3.95,Recommended
30,Uncle K Paskal,Bandung,4.2,3.6,3.90,Recommended
31,Kopi Scooter Singapore Kopitiam,Bandung,4.2,3.4,3.80,Recommended
32,Ka Soh Restaurant Tunjungan Plaza,Surabaya,3.9,3.6,3.75,Recommended
33,Warung Mie Fook You,Badung,4.8,0.0,2.40,Reconsider
34,"BABA Street,",Badung,4.8,0.0,2.40,Reconsider
35,LONGJI,Denpasar,4.3,0.0,2.15,Reconsider
36,Roti John Singapore,Malang,4.2,0.0,2.10,Reconsider
37,Red Bowl Resto,Malang,4.0,0.0,2.00,Reconsider