# Stekhouse Overall Rating 

Here is the counting rate from various platform website, this time I'll be using Google Maps and Zomato. The sections will be divided based on genre : Western, Western Specialized, Fushioned, and Local. As we can see, Local Steakhouse are the most available in this Jakarta area, whereas Western Specialized and Fushioned are the least.

In [8]:
import pandas as pd
from pandasql import sqldf
steak = pd.read_csv('../input/steakhouse-jakarta/Steakhouse.csv', sep = ";")

# Western Section

Based on total rating, the highest is **Cut & Grill (Tebet, South Jakarta)** which scored 4.6 from 3086 votes, also the best among South Jakarta's Western Steakhouse. 

If being divided for city representative, **Tony Roma's (Thamrin)** is the best western steak from Central Jakarta, scored 4.55 from 1047 votes. **B'Steak Grill & Pancake Green Ville** has the highest rating among West Jakarta's Western style steakhouse, scored 4.55 from 2618 votes. Rest of them is **Street Steak (Kelapa Gading)** from North Jakarta scored 4.5 from 1919 votes.

In [2]:
steak = sqldf("""SELECT restaurant_name, city, district, ltrim(google_rating) as google_rating, 
ltrim(platform_rating) as platform_rating,
ltrim((google_rating + platform_rating)/2) as total_rating,
ltrim(google_count + platform_count) as total_count,
CASE
    WHEN (google_rating + platform_rating)/2 >= 3.5 THEN "Recommended"
    ELSE "Reconsidered"
    END AS "Recommendation"
FROM steak WHERE specialized = "Western"
ORDER BY total_rating DESC;""")
steak.style.hide_index()

# Western Specialized Section

As for Western Specialized Section, **Tucano's Churrascaria Sudirman**, whom serving Brazilian-style steak buffet is the best among list (scored 4.7 from 1107 votes), also best among Central Jakarta on this section. **Carbon**, which serving Mexican food got 4.5 from 165 votes within South Jakarta area. 

For other genre, best Italian restaurant is **Caffe Milano** (Thamrin, scored 4.45 from 1869 votes), meanwhile for French restaurant **Cafe de Paris (Kebayoran Lama)** is the most worth to try (scored 3.6 from 37 votes).

In [5]:
steak = sqldf("""SELECT restaurant_name, specialized, city, district, ltrim(google_rating) as google_rating, 
ltrim(platform_rating) as platform_rating,
ltrim((google_rating + platform_rating)/2) as total_rating,
ltrim(google_count + platform_count) as total_count,
CASE
    WHEN (google_rating + platform_rating)/2 >= 3.5 THEN "Recommended"
    ELSE "Reconsidered"
    END AS "Recommendation"
FROM steak 
WHERE specialized = 'Brazilian' OR specialized = 'Mexican' OR specialized = 'Argentinian' 
OR specialized = 'Italian' OR specialized = 'French'
ORDER BY total_rating DESC;""")
steak.style.hide_index()

# Fushioned

In this section, **Sumibi (Gandaria)** won the best restaurant among fushioned restaurant, scored 4.65 from 1655 votes, also the best for Japanese restaurant and South Jakarta area. **Benihana Japanese Steakhouse (Thamrin)** scored 4.45 from 410 votes, made them the highest rangking thorough Central Jakarta. As for North Jakarta, they have **Pepperloin Steakhouse** which scored 4.35 from 1015 votes.

For other genre, **VIN+ Wine & Beyond (Kemang)** won the most for Indonesian fushion, scored 4.4 from 1724 votes. **Ninety Nine (Thamrin, Grand Indonesia)** won for fushioned Indonesian and Singaporean, scored 4.3 from 655 votes. **Greyhond Cafe (Thamrin, Grand Indonesia)** is the only one Thailand fushioned restaurant among this list (scored 4.3 from 1576 votes).

In [7]:
steak = sqldf("""SELECT restaurant_name, fushioned, city, district, ltrim(google_rating) as google_rating, 
ltrim(platform_rating) as platform_rating,
ltrim((google_rating + platform_rating)/2) as total_rating,
ltrim(google_count + platform_count) as total_count,
CASE
    WHEN (google_rating + platform_rating)/2 >= 3.5 THEN "Recommended"
    ELSE "Reconsidered"
    END AS "Recommendation"
FROM steak 
WHERE fushioned NOT LIKE '%no'
ORDER BY total_rating DESC;""")
steak.style.hide_index()

# Local Section

This is the most interesting section, which is the most restaurant available thorough Jakarta area. In this section, **Holycow! Kebon Jeruk** won the most which scored 4.55 from 4601 votes, also the best among Local Western and West Jakarta area. For local section, **Joni Steak (Gajah Mada)** won the section with score 4.3 from 5638 votes, also the best local steak in Central Jakarta and thorough Jakarta area.

**Holycow! Kalimalang** (scored 4.4 from 2562 votes) and **Waroeng Steak & Shake Kalimalang** (scored 3.95 from 3532 votes) is the best for both local westerned and local restaurant among East Jakarta area. **The Real Holysteak** (scored 4.35 from 471 votes) and **Andakar** (scored 4.3 from 2661 votes) also the best among South Jakarta area for both local westerned and local restaurant. 

Last but not least, **The Garden** (scored 4.45 from 3268 votes) and **Meaters Steak & Ribs** (scored 4.2 from 744 votes) are the best for both local westerned and local restaurant in North Jakarta area.

In [9]:
steak = sqldf("""SELECT restaurant_name, specialized, city, district, ltrim(google_rating) as google_rating, 
ltrim(platform_rating) as platform_rating,
ltrim((google_rating + platform_rating)/2) as total_rating,
ltrim(google_count + platform_count) as total_count,
CASE
    WHEN (google_rating + platform_rating)/2 >= 3.5 THEN "Recommended"
    ELSE "Reconsidered"
    END AS "Recommendation"
FROM steak 
WHERE specialized = 'Local' OR specialized = 'Local Westerned'
ORDER BY total_rating DESC;""")
steak.style.hide_index()